datalust/seqcli

- src/SeqCli/Cli/Commands/QueryCommand.cs
- src/SeqCli/Cli/Features/OutputFormatFeature.cs
- src/SeqCli/Csv/CsvToken.cs
- src/SeqCli/Csv/CsvTokenizer.cs
- src/SeqCli/Csv/CsvWriter.cs
- src/SeqCli/SeqCli.csproj
- test/SeqCli.Tests/Csv/CsvTokenizerTests.cs
- test/SeqCli.Tests/SeqCli.Tests.csproj
A bit of a mash-up, but seems to do a good job of making CSV query results a bit more readable. Disable with `--no-color`.
> Serilog console themes + quick CSV tokenizer -> nicer query results

- src/SeqCli/Cli/Features/OutputFormatFeature.cs
- src/SeqCli/Output/RedundantEventTypeRemovalEnricher.cs
- src/SeqCli/Program.cs
(At least while the bugs are being shaken out; this will probably turn into a --verbose flag.)
> Tidy up tail output; output verbose error information 

- nuget.config
- seqcli.sln
- src/SeqCli/SeqCli.csproj
Seeing the following in published binaries only:
```
System.Net.WebSockets.WebSocketException (0x80004005): Unable to connect to the remote server ---> System.IO.IOException: Unable to write data to the transport connection: The lazily-initialized type does not have a public, parameterless constructor.. ---> System.MissingMemberException: The lazily-initialized type does not have a public, parameterless constructor.
at System.Threading.LazyHelpers`1.ActivatorFactorySelector()
at System.Threading.LazyInitializer.EnsureInitializedCore[T](T& target, Func`1 valueFactory)
at System.Net.Sockets.Socket.RentSocketAsyncEventArgs(Boolean isReceive)
at System.Net.Sockets.Socket.SendAsync(ArraySegment`1 buffer, SocketFlags socketFlags, Boolean fromNetworkStream)
at …
```
> Remove ILLink

- src/SeqCli/Csv/CsvTokenizer.cs
- src/SeqCli/PlainText/Frame.cs
- src/SeqCli/PlainText/FrameReader.cs
- src/SeqCli/SeqCli.csproj
- test/SeqCli.Tests/PlainText/FrameReaderTests.cs
This PR establishes a way of reading logs in real-time from STDIN; the eventual usage will be:
```
./myapp | seqcli ingest --plain
```
The major requirement dealt with here is the need to ingest multi-line messages; we do this by:
* Establishing what the start of a message ("frame") will look like, via a `TextParser<TextSpan>`
* Reading from the start of a message until we see the start of the next message, or, until a timed deadline elapses
This ensures that output like:
```
Error: System.InvalidOperationException: failed!
at a.cs
at b.cs
```
can be read into a single frame, without waiting for another message to confirm that no further stack trace lines are coming.
Not the most efficient implementation, but does successfully avoid synchronization.
One snag, the …
> Plain text ingestion WIP: read frames of input with trailing lines

- src/SeqCli/Cli/Commands/LogCommand.cs
This is normally handled by `SeqConnection`, but we're bypassing it here so we need to add the header manually.
> Ensure API key is passed via the command

- src/SeqCli/Cli/CommandAttribute.cs
- src/SeqCli/Cli/CommandLineHost.cs
- src/SeqCli/Cli/CommandMetadata.cs
- src/SeqCli/Cli/ICommandMetadata.cs
- test/SeqCli.Tests/Cli/CommandLineHostTests.cs
- test/SeqCli.Tests/Cli/NoDuplicateCommands.cs
This is designed to allow for the first proposal in https://github.com/datalust/seqcli/issues/2.
I am building a proposal for API Key management which is where this came from.
```
seqcli apikey list
seqcli apikey get -n="ApplicationName"
```
> Add support for a subcommand

- src/SeqCli/Cli/Commands/ApiKey/ListCommand.cs
- src/SeqCli/Cli/Commands/ApiKey/RemoveCommand.cs
This is an initial idea for listing and removing of API Keys it is based on my work in #26. I plan on adding support for adding api keys.
> Add support for Listing and Removing API Keys

- README.md
- src/SeqCli/PlainText/Extraction/ExtractionPatternInterpreter.cs
- src/SeqCli/PlainText/Extraction/GroupedPatternElement.cs
- src/SeqCli/PlainText/Extraction/Matchers.cs
- src/SeqCli/PlainText/Extraction/NameValueExtractor.cs
- src/SeqCli/PlainText/Extraction/PatternElement.cs
- src/SeqCli/PlainText/Extraction/SimplePatternElement.cs
- src/SeqCli/PlainText/Patterns/ExtractionPatternParser.cs
- src/SeqCli/PlainText/Patterns/GroupedContentExpression.cs
- test/SeqCli.Tests/PlainText/ExtractionPatternParserTests.cs
- test/SeqCli.Tests/PlainText/NameValueExtractorTests.cs
These are still very basic and incomplete (especially the library of built-in matchers, which needs to be extended and documented). But - it's definitely enough now to start trying to tackle some more log formats.
(In addition to a table of named matchers, I'm hoping we'll get some examples like the Apache access log format documented down the track.)
> Compound patterns

- README.md
- src/SeqCli/Cli/CommandLineHost.cs
- src/SeqCli/Cli/Commands/ApiKey/ListCommand.cs
- src/SeqCli/Cli/Commands/ApiKey/RemoveCommand.cs
- src/SeqCli/Cli/Commands/HelpCommand.cs
- src/SeqCli/Cli/Features/OutputFormatFeature.cs
- src/SeqCli/Output/StripStructureTypeEnricher.cs
- src/SeqCli/SeqCli.csproj
- test/SeqCli.Tests/Cli/CommandLineHostTests.cs
Had a shot at generic output formatting for entities, i.e. what we'll get from `apikey list` type commands:
The results are okay - there are three modes, text (Id/Title pair), JSON (colorized via Serilog...) and plain JSON. It's a hideously inefficient way to output JSON, but not _too_ bad to read. An `--indented` option might be desirable someday.
~~Hacked in~~Sorted out the `seqcli help <command> <subcommand>` functionality en route.
> Generic entity formatting

- src/SeqCli/Cli/Commands/IngestCommand.cs
- src/SeqCli/Ingestion/BatchResult.cs
- src/SeqCli/Ingestion/ClefLogEventReader.cs
- src/SeqCli/Ingestion/ILogEventReader.cs
- src/SeqCli/Ingestion/LogShipper.cs
- src/SeqCli/Ingestion/ReadResult.cs
- src/SeqCli/PlainText/Extraction/ExtractionPatternInterpreter.cs
- src/SeqCli/PlainText/Extraction/Matchers.cs
- src/SeqCli/PlainText/Framing/Frame.cs
- src/SeqCli/PlainText/Framing/FrameReader.cs
- src/SeqCli/PlainText/PlainTextLogEventReader.cs
- test/SeqCli.Tests/PlainText/FrameReaderTests.cs
- test/SeqCli.Tests/PlainText/NameValueExtractorTests.cs
Fixes #33 
When logs are streamed to `seqcli ingest`, partial batches need to be sent rather than waiting for a complete batch from STDIN.
This is achieved using `FrameReader`, which sets a new property `IsAtEnd` on `Frame` - each attempt to read a new line will now time out in 10ms and the batching logic send any accumulated events that have been queued.
There's still room for refactoring and improvement here, but we should be closer to working respectably, now :-)
Switches JSON ingestion to this mode also.
> Don't block while partial batches are read from STDIN

- src/SeqCli/Cli/Commands/IngestCommand.cs
- src/SeqCli/Ingestion/BatchResult.cs
- src/SeqCli/Ingestion/ClefLogEventReader.cs
- src/SeqCli/Ingestion/ILogEventReader.cs
- src/SeqCli/Ingestion/LogShipper.cs
- src/SeqCli/Ingestion/ReadResult.cs
- src/SeqCli/PlainText/Extraction/ExtractionPatternInterpreter.cs
- src/SeqCli/PlainText/Extraction/Matchers.cs
- src/SeqCli/PlainText/Framing/Frame.cs
- src/SeqCli/PlainText/Framing/FrameReader.cs
- src/SeqCli/PlainText/Patterns/MatchTypeContentExpression.cs
- src/SeqCli/PlainText/PlainTextLogEventReader.cs
- test/SeqCli.Tests/PlainText/FrameReaderTests.cs
- test/SeqCli.Tests/PlainText/MatchersTests.cs
- test/SeqCli.Tests/PlainText/NameValueExtractorTests.cs
The following now work on my default/Australian English Ubuntu 17.10 box:
```shell
journalctl -f -n 0 |
seqcli ingest -x "{@t:syslogdt} {host} {ident:*}: {@m:*}{:n}" --invalid-data=ignore
tail -c 0 -F /var/log/syslog |
seqcli ingest -x "{@t:syslogdt} {host} {ident:*}: {@m:*}{:n}"
```
The output is not _pretty_, but it's a start!
Fixes #34 Depends on #35
> Basic systemd/syslog ingestion

- README.md
- src/SeqCli/Config/SeqCliConnectionConfig.cs
- src/SeqCli/Util/UserScopeDataProtection.cs
Fixes #40 
Avoids attempting to call Windows APIs when using API keys by not encrypting them on non-Windows platforms. Where should we call out that non-Windows platforms won't have their API keys encrypted in the configuration?
> Only encrypt api key variable on windows

- src/SeqCli/Cli/Commands/IngestCommand.cs
- src/SeqCli/Cli/Features/SendFailureHandlingFeature.cs
- src/SeqCli/Ingestion/LogShipper.cs
- src/SeqCli/Ingestion/SendFailureHandling.cs
Three options are added; `--send-failure=fail` - the default, `continue` or (silently) `ignore`.
Usage:
```shell
tail -c 0 -F /var/log/syslog |
seqcli ingest \
-x "{@t:syslogdt} {host} {ident:*}: {@m:*}{:n}" \
-p source=syslog \
--send-failure=continue
```
(For #37 to be complete, a `retry` option is needed, but this will mean rethinking the way backpressure is currently handled, and probably require some buffering.)
> Option to ignore connection issues during ingestion

- seqcli.sln
- src/SeqCli/PlainText/Extraction/Matchers.cs
- src/SeqCli/Program.cs
- test/SeqCli.EndToEnd/Args.cs
- test/SeqCli.EndToEnd/LogCommand/LogCommandBasicsTestCase.cs
- test/SeqCli.EndToEnd/Program.cs
- test/SeqCli.EndToEnd/SeqCli.EndToEnd.csproj
- test/SeqCli.EndToEnd/Support/CaptiveProcess.cs
- test/SeqCli.EndToEnd/Support/CliCommandRunner.cs
- test/SeqCli.EndToEnd/Support/ICliTestCase.cs
- test/SeqCli.EndToEnd/Support/ITestProcess.cs
- test/SeqCli.EndToEnd/Support/IsolatedTestCase.cs
- test/SeqCli.EndToEnd/Support/SeqConnectionExtensions.cs
- test/SeqCli.EndToEnd/Support/TestConfiguration.cs
- test/SeqCli.EndToEnd/Support/TestDataFolder.cs
- test/SeqCli.EndToEnd/Support/TestDriver.cs
- test/SeqCli.EndToEnd/TestDriverModule.cs
- test/SeqCli.Tests/PlainText/MatchersTests.cs
Fixes #30 
This allows us to write tests like:
```csharp
public class LogCommandBasicsTestCase : ICliTestCase
{
public async Task ExecuteAsync(
SeqConnection connection,
ILogger logger,
CliCommandRunner runner)
{
var exit = runner.Exec("log", "-m 'Hello, {Name}!' -p Name=world");
Assert.Equal(0, exit);
var events = await connection.Events.ListAsync(render: true, filter: "Name = 'world'");
Assert.Single(events);
var hello = events.Single();
Assert.Equal("Hello, world!", hello.RenderedMessage);
}
}
```
Current caveats:
* Assumes there's a `seq` binary on the `PATH`
* Really only viable to run on Windows
* Not yet invoked from CI
> End-to-end test harness

- src/SeqCli/Cli/Commands/IngestCommand.cs
- src/SeqCli/Ingestion/JsonLogEventReader.cs
- src/SeqCli/PlainText/Framing/FrameReader.cs
- test/SeqCli.EndToEnd/Data/events.clef
- test/SeqCli.EndToEnd/Data/events.ndjson
- test/SeqCli.EndToEnd/Data/events.txt
- test/SeqCli.EndToEnd/IngestCommand/NDJsonIngestionTestCase.cs
- test/SeqCli.EndToEnd/IngestCommand/SimpleTextIngestionTestCase.cs
- test/SeqCli.EndToEnd/IngestCommand/StrictClefIngestionTestCase.cs
- test/SeqCli.EndToEnd/SeqCli.EndToEnd.csproj
- test/SeqCli.EndToEnd/Support/IsolatedTestCase.cs
- test/SeqCli.EndToEnd/Support/SeqConnectionExtensions.cs
- test/SeqCli.EndToEnd/Support/TestConfiguration.cs
- test/SeqCli.EndToEnd/Support/TestDriver.cs
Fixes #46. Any JSON document is now accepted as an event by `ingest --json`.
> JSON ingestion, more test coverage

- src/SeqCli/SeqCli.csproj
The pre-release v5 _Seq.Api_ package that this app depends upon caused problems when sending `SignalEntity` payloads due to an invalid `null` value for the renamed `IsRestricted` property. Updating the package fixes this.
> Update Seq.Api.dll; fixes #60

- src/SeqCli/Cli/Commands/Dashboard/ListCommand.cs
- src/SeqCli/Cli/Commands/Dashboard/RemoveCommand.cs
- src/SeqCli/Cli/Commands/Signal/ImportCommand.cs
- src/SeqCli/Cli/Commands/Signal/ListCommand.cs
- src/SeqCli/Cli/Commands/Signal/RemoveCommand.cs
- src/SeqCli/Cli/Commands/TailCommand.cs
- src/SeqCli/Cli/Features/EntityOwnerFeature.cs
- src/SeqCli/SeqCli.csproj
- test/SeqCli.EndToEnd/Signal/SignalBasicsTestCase.cs
This is required for compatibility with Seq 5 beta 2, which will be out shortly.
Example usage:
```
seqcli signal list
seqcli signal list -o user-admin
```
> Allow owner to be specified when searching for shareable items

- src/SeqCli/Api/ApiConstants.cs
- src/SeqCli/Cli/Commands/IngestCommand.cs
- src/SeqCli/Cli/Commands/LogCommand.cs
- src/SeqCli/Connection/SeqConnectionFactory.cs
- src/SeqCli/Ingestion/LogShipper.cs
This PR fixes a bug causing API keys not to be sent by the `seqcli ingest` command, and the default API in _SeqCli.json_ to be ignored by `seqcli log`.
Ideally, _Seq.Api_ should be extended to cover these use cases in the future.
> Send API key correctly when logging/ingesting

- dockerfiles/seqcli/.gitignore
- dockerfiles/seqcli/Dockerfile
- dockerfiles/seqcli/run.sh
This `Dockerfile` expects the `seqcli-{version}-linux-x64.tar.gz` to bundle into a container. Having a container for `seqcli` will be helpful for workflows that are already built on Docker.
> Add an initial dockerfile

- test/SeqCli.EndToEnd/ApiKey/ApiKeyCreateTestCase.cs
This was missed in the last PR. SUT code is fine, but the test case is broken.
> Fix test case covering API key JSON output formatting

- src/SeqCli/PlainText/Extraction/Matchers.cs
- test/SeqCli.Tests/PlainText/MatchersTests.cs
Accepts timestamps like `2019-01-02 03:04:05` as UTC timestamps.
> Added `w3cdt` W3C/IIS log file timestamp matcher

- src/SeqCli/Apps/AppHost.cs
- src/SeqCli/Cli/Commands/App/RunCommand.cs
- src/SeqCli/Cli/Commands/PrintCommand.cs
- src/SeqCli/Cli/Features/OutputFormatFeature.cs
- src/SeqCli/PlainText/Framing/FrameReader.cs
- src/SeqCli/Program.cs
- src/SeqCli/SeqCliModule.cs
```
> seqcli help print
seqcli print [<args>]
Pretty-print events in CLEF/JSON format, from a file or `STDIN`
Arguments:
-i, --input=VALUE          CLEF file to read, including the `*` wildcard; if
not specified, `STDIN` will be used
-f, --filter=VALUE         Filter expression to select a subset of events
--template=VALUE       Specify an output template to control plain text
formatting
--invalid-data=VALUE   Specify how invalid data is handled: `fail` (
default) or `ignore`
--no-color             Don't colorize text output
```
> Adds the seqcli print command

- README.md
- seqcli.sln.DotSettings
- src/SeqCli/PlainText/Extraction/Matchers.cs
- test/SeqCli.Tests/PlainText/MatchersTests.cs
This has been omitted so far because either ` ` or `{:*}` is suitable for this in almost all cases. Looking for and thinking in terms of `{:s}` is natural, however, and there doesn't seem to be any harm in including it.
README updated with current matchers.
> Add an `:s` one-or-more whitespace matcher

- Build.Docker.ps1
- Build.ps1
- appveyor.yml
- dockerfiles/seqcli/Dockerfile
- setup.sh
This PR adds an automated Docker build and publish to our CI environment.
Images are pushed to a `datalust/seqcli-ci` repository. We can then manually promote builds to `datalust/seqcli`.
> Publish docker images in ci

- seqcli.sln.DotSettings
- src/SeqCli/PlainText/Framing/FrameReader.cs
- test/SeqCli.Tests/PlainText/FrameReaderTests.cs
Fixes #118.
Updated: fixes #122.
> Don't crash on empty trailing lines when reading frames

- src/SeqCli/Cli/Commands/HelpCommand.cs
Just a tiny fix for the markdown README generation; the fix for #124 introduced a regression causing single-command groups to show only the group name in the TOC.
Fixed in this PR; see `app run` below for an example.
```
- `apikey`
- [`apikey create`](#apikey-create) &mdash; Create an API key for ingestion.
- [`apikey list`](#apikey-list) &mdash; List available API keys.
- [`apikey remove`](#apikey-remove) &mdash; Remove an API key from the server.
- [`app run`](#app-run) &mdash; Host a .NET `[SeqApp]` plug-in.
- [`config`](#config) &mdash; View and set fields in the `SeqCli.json` file; run with no argu...
- `dashboard`
- [`dashboard list`](#dashboard-list) &mdash; List dashboards.
- [`dashboard remove`](#dashboard-remove) &mdash; Remove a dashboard from the server.
```
> Generate correct documentation TOC for command groups of only one subcommand

- src/SeqCli/Cli/Commands/Workspace/CreateCommand.cs
- src/SeqCli/Cli/Commands/Workspace/ListCommand.cs
- src/SeqCli/Cli/Commands/Workspace/RemoveCommand.cs
As referenced in [Issue 130](https://github.com/datalust/seqcli/issues/130). Added a new CLI command for workspace. These commands include:
- create
- list
- remove
Hope you find this useful. I'd be willing to have a go at implementing commands for adding and removing signals to the workspace as well if this PR looks good.
> Added create, remove and list commands for workspaces

- src/SeqCli/Apps/AppLoader.cs
- src/SeqCli/Cli/Commands/Signal/CreateCommand.cs
- src/SeqCli/Cli/Commands/Workspace/CreateCommand.cs
- src/SeqCli/Cli/Features/EntityOwnerFeature.cs
- test/SeqCli.EndToEnd/Workspace/WorkspaceBasicsTestCase.cs
This makes the last few changes to `workspace create` discussed in #131:
```
seqcli workspace create -t 'test' --signal=signal-123 --signal=signal-124 --dashboard=dashboard-456
```
Multi-arg support for `--signal` is extended to `--dashboard` and `--query`.
To get the newly-added tests to pass, it was necessary to make `workspace create` behave consistently WRT sharing. In practice, `seqcli` always creates shared signals, workspaces, and API keys. Running against test instances without authentication enabled, however, signals and workspaces would be created as owned by the admin user. Fixed this to behave consistently across all three entity types in both auth modes.
> Multiple dashboard/query support in 'worskpace create'; ensure consistent creation of shared signals and workspaces

- seqcli.sln.DotSettings
- src/SeqCli/Apps/AppLoader.cs
- src/SeqCli/Apps/Definitions/AppDefinition.cs
- src/SeqCli/Apps/Definitions/AppMetadataReader.cs
- src/SeqCli/Apps/Definitions/AppPlatformDefinition.cs
- src/SeqCli/Apps/Definitions/AppSettingDefinition.cs
- src/SeqCli/Apps/Definitions/AppSettingType.cs
- src/SeqCli/Apps/Definitions/PackageInterrogator.cs
- src/SeqCli/Apps/Hosting/AppContainer.cs
- src/SeqCli/Apps/Hosting/AppEnvironment.cs
- src/SeqCli/Apps/Hosting/AppHost.cs
- src/SeqCli/Apps/Hosting/EventFormat.cs
- src/SeqCli/Cli/Commands/App/DefineCommand.cs
- src/SeqCli/Cli/Commands/App/RunCommand.cs
- src/SeqCli/Program.cs
- src/SeqCli/SeqCli.csproj
- test/SeqCli.Tests/Apps/AppContainerTests.cs
- test/SeqCli.Tests/Apps/PackageInterrogatorTests.cs
Seq currently ships _Seq.Apps.GenericHost_ and _Seq.Apps.Interrogator_ binaries for working with .NET app packages. These two executables load and execute app packages, and read app package metadata.
In a near-future Seq release, we'd like to replace _GenericHost_ and _Interrogator_ with corresponding commands from `seqcli`. The `app run` command already implements the generic hosting functionality, with some minor feature gaps.
By closing those gaps, and adding a new `seqcli app define` command to play the role of _Interrogator_, we can remove the two standalone executables.
This will:
- Reduce the sizes of the Windows installer and Docker image
- Make the development-time app debugging infrastructure (`seqcli app run`) match the runtime app environment exactly, making behavior around …
> Extend app hosting to cover Seq requirements

- Build.ps1
- appveyor.yml
- src/SeqCli/SeqCli.csproj
> Add pack as dotnet tool

- README.md
- src/SeqCli/Cli/Commands/Signal/ImportCommand.cs
When importing signals if a signal with the same id is found it will update the values instead of inserting a new one.
Related to #145
> Allow updating signals

- seqcli.sln.DotSettings
- src/SeqCli/Apps/Hosting/AppActivator.cs
- src/SeqCli/Cli/Commands/ConfigCommand.cs
- src/SeqCli/Cli/Commands/SearchCommand.cs
- src/SeqCli/Cli/Options.cs
- src/SeqCli/Syntax/DurationMoniker.cs
In several places we assume numbers are in a JSON-like format with `.` use as the decimal separator. Commas are generally used as separators between values, rather than being in the role of decimal separators as in many international number formats.
This PR makes the assumption explicit by specifying US-style number formatting and parsing in most places.
> Specify CultureInfo.InvariantCulture wherever numeric input or formatting is relied on programmatically

- appveyor.yml
- src/SeqCli/Cli/Commands/User/CreateCommand.cs
- test/SeqCli.EndToEnd/Args.cs
- test/SeqCli.EndToEnd/Support/CaptiveProcess.cs
- test/SeqCli.EndToEnd/Support/CliTestCaseAttribute.cs
- test/SeqCli.EndToEnd/Support/IsolatedTestCase.cs
- test/SeqCli.EndToEnd/Support/IsolatedTestCaseRegistrationSource.cs
- test/SeqCli.EndToEnd/Support/LicenseCliSetupTestCase.cs
- test/SeqCli.EndToEnd/Support/TestConfiguration.cs
- test/SeqCli.EndToEnd/Support/TestDriver.cs
- test/SeqCli.EndToEnd/TestDriverModule.cs
- test/SeqCli.EndToEnd/User/UserCreateRemoveTestCase.cs
- test/SeqCli.EndToEnd/User/UserListTestCase.cs
Fixes #168
To run multi-user tests (we now have one!), supply a valid license through `STDIN`:
```
test\SeqCli.EndToEnd>dotnet run --license-certificate-stdin < Certificate.txt
```
There's a bit of gunk required to get `[CliTestCase(Multiuser = true)]` propagated through Autofac, and argument handling isn't great. I'm out of time now but will come around and take another shot at it down the line :)
> Fix seqcli user create (#168); add multi-user testing support to the end-to-end tests

- README.md
- src/SeqCli/PlainText/Extraction/Matchers.cs
- test/SeqCli.Tests/PlainText/MatchersTests.cs
This adds support for a Unix timestamp matcher. I've seen this format use seconds or milliseconds in the wild so I've used a simple opinionated cutoff for switching between the two based on the length of the field value. This has worked well in my use but I'm open to other strategies.
I basically took the approach of assuming log data was more likely _recent_ in nature, and so the length of 13 was chosen as the edge between seconds and milliseconds. 
Using these maximum values you can see the range of each in terms of ms:
- 9999999999999 (13 digits) means Sat Nov 20 2286 17:46:39 UTC
- 999999999999 (12 digits) means Sun Sep 09 2001 01:46:39 UTC
- 99999999999 (11 digits) means Sat Mar 03 1973 09:46:39 UTC
If we are to assume log data is typically not older than 2001, we should be safe to …
> Adds support for unixdt matcher

- src/SeqCli/Cli/Commands/SearchCommand.cs
Fixes #169 
No integration test for this; we don't currently run automated tests against a large enough data set to exercise it.
> Respect --count parameter when returning paged result sets through seqcli search

- appveyor.yml
- src/SeqCli/SeqCli.csproj
Just a version bump - we rolled the new features slated for release in 2021.2 into the last 2021.1 patch:
https://github.com/datalust/seqcli/releases/tag/v2021.1.439
> 2021.2.0 Release

- Build.ps1
The last release regressed .NET tool publishing by adding the `net5.0-windows` TFM.
The fix here is to clear this out when performing pack-as-tool, and specifying `TargetFramework=net5.0`.
> Fix tool publishing - requires a single platform-independent TFM

- src/SeqCli/SeqCli.csproj
Just re-enables tool package publishing:
* #183 - fix publishing of the `dotnet` global tool package
> 2021.2 Maintenance Release

- src/SeqCli/Cli/Commands/IngestCommand.cs
- src/SeqCli/Cli/Commands/Sample/IngestCommand.cs
- src/SeqCli/Cli/Features/BatchSizeFeature.cs
- src/SeqCli/Ingestion/LogShipper.cs
- src/SeqCli/Sample/Loader/Simulation.cs
The default batch size of 100 is ok for live scenarios, but can make ingestion of historical data slower than it needs to be (where each batch requires a couple of fsyncs).
This PR makes the batch size configurable while retaining the current as a default.
> Make the ingestion batch size configurable

- src/SeqCli/Cli/Commands/Feed/CreateCommand.cs
- src/SeqCli/Cli/Commands/Feed/ListCommand.cs
- src/SeqCli/Cli/Commands/Feed/RemoveCommand.cs
- src/SeqCli/Cli/Commands/User/CreateCommand.cs
- test/SeqCli.EndToEnd/Feed/FeedBasicsTestCase.cs
```
> seqcli help feed
Usage: seqcli feed <sub-command> [<args>]
Available sub-commands are:
create     Create a NuGet feed
list       List NuGet feeds
remove     Remove a NuGet feed from the server
Type `seqcli help feed <sub-command>` for detailed help
> seqcli help feed create
seqcli feed create [<args>]
Create a NuGet feed
Arguments:
-n, --name=VALUE           A unique name for the feed
-l, --location=VALUE       The feed location; this may be a NuGet v2 or v3
feed URL, or a local filesystem path on the
Seq server
-u, --username=VALUE       The username Seq should supply when connecting to
the feed, if authentication is required
-p, --password=VALUE       A feed password, if authentication is required;
note that `--password-stdin` is more secure
--password-stdin       Read the feed …
```
> `seqcli feed (create|list|remove)` commands

- src/SeqCli/Cli/Commands/ApiKey/CreateCommand.cs
- src/SeqCli/Cli/Commands/User/CreateCommand.cs
- src/SeqCli/Util/ArgumentString.cs
- test/SeqCli.EndToEnd/ApiKey/ApiKeyDelegatePermissionsTestCase.cs
- test/SeqCli.EndToEnd/Support/TestDriver.cs
Fixes #188
This enables:
```
seqcli apikey create -t First --token="yourtokenhere" --connect-username=admin --connect-password=password --permissions="Read,Write,Setup"
```
~~Some form of testing still outstanding.~~ ✔️
> Connect as a named user when creating the first API key

- seqcli.sln.DotSettings
- src/SeqCli/Cli/Commands/RetentionPolicy/CreateCommand.cs
- src/SeqCli/Cli/Commands/RetentionPolicy/ListCommand.cs
- src/SeqCli/Cli/Commands/RetentionPolicy/RemoveCommand.cs
- src/SeqCli/Syntax/DurationMoniker.cs
- test/SeqCli.EndToEnd/RetentionPolicy/RetentionPolicyBasicsTestCase.cs
Retention policy setup is quite fundamental, but missing from `seqcli`.
The requirement to specify removed signal expressions makes this task quite involved; this PR is just an "MVP" to get us started. Only `--delete-all-events` is supported. This will provide enough of a foundation that we can add full signal name/signal expression support in a follow-up.
```
> seqcli help retention
Usage: seqcli retention <sub-command> [<args>]
Available sub-commands are:
create     Create a retention policy
list       List retention policies
remove     Remove a retention policy from the server
Type `seqcli help retention <sub-command>` for detailed help
> seqcli help retention create
seqcli retention create [<args>]
Create a retention policy
Arguments:
--after=VALUE          A duration after which the …
```
> `seqcli retention (create|list|remove)`

- seqcli.sln.DotSettings
- src/SeqCli/Cli/Commands/License/ApplyCommand.cs
- src/SeqCli/Util/ArgumentString.cs
- test/SeqCli.EndToEnd/License/LicenseApplyTestsCasecs.cs
- test/SeqCli.EndToEnd/Support/LicenseCliSetupTestCase.cs
- test/SeqCli.EndToEnd/Support/TestDataFolder.cs
```
seqcli license apply [<args>]
Apply a license to the Seq server
Arguments:
-c, --certificate=VALUE    Certificate file; the file must be UTF-8 text
--certificate-stdin    Read the license certificate from `STDIN`
--automatically-refresh
If the license is for a subscription,
periodically check `datalust.co` and
automatically refresh the certificate when the
subscription is changed or renewed
-s, --server=VALUE         The URL of the Seq server; by default the `
connection.serverUrl` config value will be used
-a, --apikey=VALUE         The API key to use when connecting to the server;
by default the `connection.apiKey` config
value will be used
--profile=VALUE        A connection profile to use; by default the `
connection.serverUrl` and `connection.apiKey`
config values will be used …
```
> `seqcli license apply`

- src/SeqCli/Cli/Command.cs
- src/SeqCli/Cli/CommandLineHost.cs
- src/SeqCli/Cli/Commands/Node/DemoteCommand.cs
- src/SeqCli/Cli/Commands/Node/HealthCommand.cs
- src/SeqCli/Cli/Commands/Node/ListCommand.cs
- src/SeqCli/Cli/Commands/SearchCommand.cs
- src/SeqCli/Cli/Commands/TailCommand.cs
- src/SeqCli/Cli/Commands/VersionCommand.cs
- src/SeqCli/Cli/Features/ConnectionFeature.cs
- src/SeqCli/Connection/SeqConnectionFactory.cs
- src/SeqCli/Program.cs
- src/SeqCli/Util/Presentation.cs
- test/SeqCli.EndToEnd/Node/NodeDemoteTestCase.cs
- test/SeqCli.EndToEnd/Node/NodeHealthTestCase.cs
- test/SeqCli.EndToEnd/Node/NodeListTestCase.cs
- test/SeqCli.EndToEnd/Support/CliCommandRunner.cs
- test/SeqCli.Tests/Cli/CommandLineHostTests.cs
```
> seqcli node list
clusternode-7c368fb0dd3d47f2b7431a268ddd1573 seq002.datalust.example.com
clusternode-1f90287152a4098aac97fa445465c58 seq001.datalust.example.com
> seqcli node list --json
{"Role": "Leader", "Name": "seq002.datalust.example.com", "Generation": "0:0", 
"IsUpToDate": null, "MillisecondsSinceLastSync": null, "StateDescription": "The 
node is online.", "Id": "clusternode-7c368fb0dd3d47f2b7431a268ddd1573"}
{"Role": "Follower", "Name": "seq001.datalust.example.com", "Generation": "0:0", 
"IsUpToDate": true, "MillisecondsSinceLastSync": 272, "StateDescription": null,
"Id": "clusternode-1f90287152a4098aac97fa445465c58"}
> seqcli node health
HTTP 1.1 200 OK
Transfer-Encoding: chunked
Server: Microsoft-HTTPAPI/2.0
Date: Thu, 09 Sep 2021 04:51:46 GMT
Content-Type: …
```
> node list, node health, node demote commands; -v universal verbose option

- Build.Docker.ps1
- README.md
- src/SeqCli/Cli/Commands/ApiKey/CreateCommand.cs
- src/SeqCli/Cli/Commands/Signal/CreateCommand.cs
- test/SeqCli.EndToEnd/Signal/SignalCreateTestCase.cs
Solves #146
This adds an option, -c or -columns, to the seqcli signal create command.
> Add columns as an option when creating signals

- README.md
- src/SeqCli/Cli/Command.cs
- src/SeqCli/Cli/CommandLineHost.cs
- src/SeqCli/Cli/Commands/Node/DemoteCommand.cs
- test/SeqCli.EndToEnd/Node/NodeDemoteTestCase.cs
- test/SeqCli.Tests/Cli/CommandLineHostTests.cs
https://github.com/datalust/seqcli/pull/207 introduced a universal `-v|--verbose` command-line option. Unfortunately, the use of `-v` conflicts with the `--value` option accepted by `seqcli config`, breaking this (widely-used) command.
The PR removes the `-v` alias, leaving `--verbose` as the universal verbose output option.
We may reinstate this in the future if we can decide on how to reconcile these two different uses of `-v`, however with 2021.4 due within a week or so, best we make this change now.
The lack of an ability to override the storage location for `config` means this isn't currently testable using isolated end-to-end tests. We should consider following up with this capability in a future version.
> Fix `seqcli config` (regression in 2021.3.)

- Build.ps1
Seems like AppVeyor may ignore exit codes from `pwsh` scripts?
https://ci.appveyor.com/project/datalust/seqcli/builds/41948492/job/bp52vlyikgx8xh1x
This PR uses the more robust `throw` mechanism.
The builds script now also adds our installed .NET SDK path to `$env:PATH` (it doesn't seem that Setup.ps1 is effective in exporting it).
> Throw rather than exit when commands fail

- Build.Docker.ps1
- Build.ps1
- dockerfiles/seqcli/linux-arm64.Dockerfile
- dockerfiles/seqcli/linux-x64.Dockerfile
- seqcli.sln
- src/SeqCli/SeqCli.csproj
- test/SeqCli.EndToEnd/SeqCli.EndToEnd.csproj
- test/SeqCli.Tests/SeqCli.Tests.csproj
Part of #227 
We don't really need to be explicit about architectures we support in the csproj files themselves, since there's no native code or conditional compilation involved.
We now also publish Docker containers for both x86 and ARM that can be used by independent Seq apps as a base image.
> Refactor target platforms and add ARM docker publishing

- Build.Docker.ps1
- docker-publish.ps1
From 2022, we'll publish multi-architecture manifests instead of regular images. To do this:
* In CI, we'll produce `datalust/seqcli-ci:2022.n.m-x64` and `datalust/seqcli-ci:2022.n.m-arm64`
* When publishing, these two images will be packaged into `datalust/seqcli:2022.n.m`, along with `:latest` tags etc.
> Line up CI and Docker publishing scripts; publish multi-arch manifests

- Build.Docker.ps1
- appveyor.yml
- setup.sh
For #227 
It looks like we're not actually building cross-platform containers for seqcli in CI here. Running the build script locally does seem to do the right thing though, so this PR calls `buildx` directly and specifies a platform explicitly to make sure we're doing what we expect.
> Ensure we use buildx for cross-platform docker builds

- src/SeqCli/Cli/Commands/PrintCommand.cs
- src/SeqCli/Cli/Features/OutputFormatFeature.cs
- src/SeqCli/Config/SeqCliOutputConfig.cs
Allow redirected output to be colourised using ANSI control codes. Option is enabled by the `--force-color` command line switch, or by setting `output.forceColor` to `True` in `SeqCli.json`. Addresses issue #239.
In PowerShell, the following should produce colorised output (if your console supports it) where previously it would not:
gc logfile.clef | seqcli print --force-color | %{ $_ }
The value of the `--no-color` switch (or `output.disableColor` setting) will take precedence. If either one is specified, `--force-color` will be ignored.
Initially used the ANSI version of the `Literate` theme but it looked horrible so I switched to the `Code` theme.
> Colourise Redirected Output

- src/SeqCli/Cli/Commands/ApiKey/CreateCommand.cs
Just noticed that the help text for this one was a little misleading.
> Better description for `apikey create`

- CONTRIBUTING.md
- README.md
- seqcli.sln
- src/SeqCli/Cli/Commands/Sample/SetupCommand.cs
- test/SeqCli.EndToEnd/Sample/SampleSetupTestCase.cs
- test/SeqCli.EndToEnd/Support/TestConfiguration.cs
Fixes a bug (https://github.com/datalust/seqcli/issues/200) that stops `seqcli sample ingest` from working if authentication is enabled and there is exactly one user.
> Don't set owner on `seqcli sample setup` template items.

- Build.Docker.ps1
For #227 
It looks like we're bundling for `arm/v8` rather than `arm64/v8`. The former does appear to work, but can cause platform mismatches when attempting to actually pull on ARM hosts.
> target arm64/v8 rather than arm/v8

- src/SeqCli/Cli/Commands/App/InstallCommand.cs
- src/SeqCli/Cli/Commands/App/UpdateCommand.cs
- src/SeqCli/Cli/Commands/HelpCommand.cs
- test/SeqCli.EndToEnd/App/AppBasicsTestCase.cs
- test/SeqCli.EndToEnd/Feed/FeedBasicsTestCase.cs
```
seqcli app install [<args>]
Install an app package
Arguments:
--package-id=VALUE     The package id of the app to install
--version=VALUE        The package version to install; the default is to
install the latest version
--feed-id=VALUE        The id of the NuGet feed to install the package
from; may be omitted if only one feed is
configured
-s, --server=VALUE         The URL of the Seq server; by default the `
connection.serverUrl` config value will be used
-a, --apikey=VALUE         The API key to use when connecting to the server;
by default the `connection.apiKey` config
value will be used
--profile=VALUE        A connection profile to use; by default the `
connection.serverUrl` and `connection.apiKey`
config values will be used
--json                 Print output in …
```
> Basic app install and app update commands

- global.json
- src/SeqCli/Ingestion/LogShipper.cs
`LogShipper` is lacking a delay or throttling mechanism when there's no work to do, so it busy-waits, continually checking the queue and posting empty batches to Seq, which burns resources all-round.
This is noticeable when running `seqcli sample ingest`, but will also be impacting `seqcli ingest`, which is used elsewhere including `datalust/seq-input-gelf` and `datalust/seq-input-syslog`.
> Don't burn CPU when there's no log shipping to do

- src/SeqCli/Templates/Import/TemplateSetImporter.cs
See #248 
Without explicitly specifying the import ordering for alerts, they're imported first and therefore ahead of any signals/app instances they might reference.
Note that alert imports are still rather clunky; those with notification channels require `-g notificationAppInstanceId=...` to be specified on the `template import` command-line, while it'd be nicer to also import/merge app instances in the long run.
> Specify alert template import ordering

- dockerfiles/seqcli/linux-arm64.Dockerfile
It looks like we missed updating the Dockerfile itself when fixing up our ARM Docker support in #246
> Fix up ARM publishing for Docker

- src/SeqCli/Cli/Commands/Bench/BenchCasesCollection.cs
- src/SeqCli/Cli/Commands/Bench/BenchCommand.cs
- test/SeqCli.EndToEnd/Bench/BenchTestCase.cs
> Bench upgrades

- src/SeqCli/Cli/Commands/Bench/BenchCase.cs
- src/SeqCli/Cli/Commands/Bench/BenchCaseTimings.cs
- src/SeqCli/Cli/Commands/Bench/BenchCases.json
- src/SeqCli/Cli/Commands/Bench/BenchCasesCollection.cs
- src/SeqCli/Cli/Commands/Bench/BenchCommand.cs
- test/SeqCli.EndToEnd/Bench/BenchTestCase.cs
* New cases - trying to cover more areas of query perf
* Dropped off the cases file hash; the queries themselves are enough to distinguish what's being run
* Log the target server version
* Compact output
* Start and end now optional (although imprecise between runs, they can be specified in the query text for casual benchmarking)
I've also included a "notes" field with each benchmark explaining what it's supposed to measure; the code doesn't use this (yet?).
> 2023.1 target cases

- src/SeqCli/Cli/Commands/Bench/BenchCaseTimings.cs
- src/SeqCli/Cli/Commands/Bench/BenchCommand.cs
The first ("cold") result for each case is an important measure of UX.
> Report the first timing for each benchmarked query

- src/SeqCli/Cli/Command.cs
- src/SeqCli/Cli/Commands/ApiKey/ListCommand.cs
- src/SeqCli/Cli/Commands/App/DefineCommand.cs
- src/SeqCli/Cli/Commands/App/ListCommand.cs
- src/SeqCli/Cli/Commands/AppInstance/CreateCommand.cs
- src/SeqCli/Cli/Commands/AppInstance/ListCommand.cs
- src/SeqCli/Cli/Commands/AppInstance/RemoveCommand.cs
- src/SeqCli/Cli/Commands/Dashboard/ListCommand.cs
- src/SeqCli/Cli/Commands/Feed/ListCommand.cs
- src/SeqCli/Cli/Commands/HelpCommand.cs
- src/SeqCli/Cli/Commands/Node/ListCommand.cs
- src/SeqCli/Cli/Commands/RetentionPolicy/ListCommand.cs
- src/SeqCli/Cli/Commands/Signal/ListCommand.cs
- src/SeqCli/Cli/Commands/User/ListCommand.cs
- src/SeqCli/Cli/Commands/Workspace/ListCommand.cs
- src/SeqCli/Cli/Features/OutputFormatFeature.cs
- src/SeqCli/Cli/Printing.cs
- test/SeqCli.EndToEnd/App/AppBasicsTestCase.cs
- test/SeqCli.EndToEnd/AppInstance/AppInstanceBasicsTestCase.cs
- test/SeqCli.EndToEnd/Signal/SignalBasicsTestCase.cs
- test/SeqCli.EndToEnd/Support/TestConfiguration.cs
```
seqcli app list [<args>]
List installed app packages
Example:
seqcli app list
Arguments:
--package-id=VALUE     The package id of the app(s) to list
-i, --id=VALUE             The id of a single app to list
--json                 Print output in newline-delimited JSON (the
default is plain text)
--no-color             Don't colorize text output
--force-color          Force redirected output to have ANSI color (
unless `--no-color` is also specified)
-s, --server=VALUE         The URL of the Seq server; by default the `
connection.serverUrl` config value will be used
-a, --apikey=VALUE         The API key to use when connecting to the server;
by default the `connection.apiKey` config
value will be used
--profile=VALUE        A connection profile to use; by default the ` …
```
> `app list`, `appinstance (create|list|remove)`

- Build.Common.ps1
- Build.Docker.ps1
- Build.ps1
- appveyor.yml
This PR appends the branch name as a suffix to builds unless the branch is `main` so that we can more easily identify builds from `dev` as being pre-releases.
> Append branch name as a suffix when build is not main

- src/SeqCli/Api/ApiConstants.cs
- src/SeqCli/Cli/Commands/IngestCommand.cs
- src/SeqCli/Cli/Commands/LogCommand.cs
- src/SeqCli/Cli/Features/OutputFormatFeature.cs
- src/SeqCli/Ingestion/LogShipper.cs
- src/SeqCli/Ingestion/SeqBuiltInNameResolver.cs
- src/SeqCli/PlainText/Extraction/ExtractionPatternInterpreter.cs
- src/SeqCli/PlainText/LogEvents/LogEventBuilder.cs
- src/SeqCli/SeqCli.csproj
- test/SeqCli.Tests/PlainText/LogEventBuilderTests.cs
Investigated https://github.com/datalust/seqcli/issues/280 and while chasing down the issue, ported filtering from the deprecated _Serilog.Filters.Expressions_ library to the newer _Serilog.Expressions_ variant. While neither is a perfect match for Seq filtering syntax, the newer implementation is better maintained, produces more intelligible error messages, and does go as far as supporting the Seq-style `ci` modifier.
There's a plug-in name resolver that maps the Seq style names like `@Message` to the CLEF-style ones like `@m`, so existing filters will be reasonably unlikely to break.
The actual bug, in `IngestCommand` is that:
```csharp
var expr = _filter.Replace("@Level", SurrogateLevelProperty.PropertyName);
```
incorrectly results in `@Level` being replaced with `@seqlevel`. Since …
> Switch seqcli ingest filtering to use Serilog.Expressions; fix filters over non-Serilog level names

- src/SeqCli/Cli/Commands/RetentionPolicy/CreateCommand.cs
- test/SeqCli.EndToEnd/AppInstance/AppInstanceBasicsTestCase.cs
- test/SeqCli.EndToEnd/RetentionPolicy/RetentionPolicyBasicsTestCase.cs
This PR introduces a `--delete` arg to `retention create` that lets you specify a signal expression to remove. It requires that exactly one of `--delete` or `--delete-all-events` is specified so it's clear what your retention policy will do.
> Support signal expressions when creating retention policies

- src/Roastery/Roastery.csproj
- src/SeqCli/SeqCli.csproj
- test/SeqCli.EndToEnd/SeqCli.EndToEnd.csproj
- test/SeqCli.Tests/SeqCli.Tests.csproj
Discovered via an update to _Seq.App.Mail_ that we haven't updated `seqcli` yet with recent Serilog changes.
I think once this is merged we should publish a preview release and pull that into the upcoming Seq 2024.1 preview.
> Update to Serilog 3.1 to allow hosting apps that depend on it

- src/SeqCli/Cli/Commands/IngestCommand.cs
- src/SeqCli/PlainText/LogEvents/LogEventBuilder.cs
- test/SeqCli.EndToEnd/Ingest/OverrideLevelIngestionTestCase.cs
In #302 we refactored a lot of how events are constructed. One existing piece of functionality that was lost was being able to specify a level to override any in the events with when ingesting. This PR restores that functionality.
> Fix up unused level property

- src/SeqCli/Cli/Commands/SearchCommand.cs
- src/SeqCli/Templates/Export/TemplateWriter.cs
Disposal is skipped if an initializer throws.
> Don't use object initializer syntax with the using statement

- src/Roastery/Data/Database.cs
- src/Roastery/Program.cs
- src/Roastery/Roastery.csproj
- src/Roastery/Web/RequestLoggingMiddleware.cs
- src/SeqCli/Ingestion/TraceConstants.cs
- src/SeqCli/Output/OutputFormatter.cs
- src/SeqCli/Sample/Loader/Simulation.cs
This PR makes `seqcli sample ingest` produce spans instead of manually measuring the time operations take. The spans produced are fairly simplistic, but provide enough context to demonstrate various features, and highlight the kinds of issues that tracing is good at surfacing.
> Add tracing to seqcli sample ingest

- Build.ps1
- src/Roastery/Roastery.csproj
- src/SeqCli/Cli/Features/OutputFormatFeature.cs
- src/SeqCli/SeqCli.csproj
- test/SeqCli.EndToEnd/SeqCli.EndToEnd.csproj
- test/SeqCli.Tests/SeqCli.Tests.csproj
This re-enables .NET tool publishing.
Fixes #315
> Enable .NET tool major-version roll-forward, update dependencies

- src/SeqCli/Cli/Features/OutputFormatFeature.cs
- src/SeqCli/SeqCli.csproj
- src/SeqCli/Util/JsonNetDestructuringPolicy.cs
Also internalizes the Destructurama.JsonNet dependency; slow-moving single-file dependency better managed at the source level.
> 2024.2 API dependency

- test/SeqCli.EndToEnd/Args.cs
- test/SeqCli.EndToEnd/Properties/launchSettings.json
- test/SeqCli.EndToEnd/Support/CliCommandRunner.cs
- test/SeqCli.EndToEnd/Support/LicenseSetup.cs
- test/SeqCli.EndToEnd/Support/TestConfiguration.cs
Adds `launchSettings.json` configurations to make switching server binary sources easier.
> Launch configurations for local executable vs Docker/latest vs Docker/preview

- src/SeqCli/Cli/Commands/App/UninstallCommand.cs
- src/SeqCli/Cli/Features/EntityIdentityFeature.cs
- test/SeqCli.EndToEnd/App/AppBasicsTestCase.cs
```
seqcli app uninstall [<args>]
Uninstall an app package
Example:
seqcli app uninstall --package-id 'Seq.App.JsonArchive'
Arguments:
--package-id=VALUE     The package id of the app package to uninstall
-i, --id=VALUE             The id of a single app package to uninstall
-s, --server=VALUE         The URL of the Seq server; by default the `
connection.serverUrl` config value will be used
-a, --apikey=VALUE         The API key to use when connecting to the server;
by default the `connection.apiKey` config
value will be used
--profile=VALUE        A connection profile to use; by default the `
connection.serverUrl` and `connection.apiKey`
config values will be used
--verbose              Print verbose output to `STDERR`
```
> `seqcli app uninstall`

- src/SeqCli/Cli/CommandAttribute.cs
- src/SeqCli/Cli/CommandLineHost.cs
- src/SeqCli/Cli/CommandMetadata.cs
- src/SeqCli/Cli/Commands/Forwarder/InstallCommand.cs
- src/SeqCli/Cli/Commands/Forwarder/RestartCommand.cs
- src/SeqCli/Cli/Commands/Forwarder/RunCommand.cs
- src/SeqCli/Cli/Commands/Forwarder/StartCommand.cs
- src/SeqCli/Cli/Commands/Forwarder/StatusCommand.cs
- src/SeqCli/Cli/Commands/Forwarder/StopCommand.cs
- src/SeqCli/Cli/Commands/Forwarder/TruncateCommand.cs
- src/SeqCli/Cli/Commands/Forwarder/UninstallCommand.cs
- src/SeqCli/Cli/Commands/HelpCommand.cs
- test/SeqCli.EndToEnd/Help/MarkdownHelpTestCase.cs
- test/SeqCli.Tests/Cli/CommandLineHostTests.cs
- test/SeqCli.Tests/Support/ActionCommand.cs
This has two general effects:
1. The `help` command will only list preview commands when the `--pre` flag is specified, and
2. Preview commands can only be invoked when `--pre` is specified.
This is the same system that Seq uses.
The PR marks the `forwarder` commands as preview, so that when we have assembled the major pieces of it, we'll be able to bring the whole thing back to `dev` a little sooner.
> Hide preview commands behind the `--pre` flag as Seq does

- README.md
- src/SeqCli/Cli/Commands/ApiKey/CreateCommand.cs
using camelCase permission strings result in the error `Unrecognized permission read`
> Pascal case permissions

- src/SeqCli/Cli/Commands/IngestCommand.cs
- src/SeqCli/Cli/Commands/PrintCommand.cs
- src/SeqCli/Cli/Commands/Signal/ImportCommand.cs
- src/SeqCli/Cli/Features/FileInputFeature.cs
Commands like `print` and `ingest` that support wildcard file input seem to imply in their help text that multiple files can be specified on the command line. However, all but the last specified file is ignored.
This is a quick fix that enables:
```
seqcli ingest .... -i foo.clef -i bar.clef -i *-logs.clef
```
> Allow the `-i <FILENAME>` argument to be specified multiple times

- src/SeqCli/Cli/Commands/Node/HealthCommand.cs
- test/SeqCli.EndToEnd/Node/NodeDemoteTestCase.cs
- test/SeqCli.EndToEnd/Node/NodeHealthTestCase.cs
- test/SeqCli.EndToEnd/Node/NodeListTestCase.cs
No `--verbose` flag - parseable JSON:
```
> seqcli -- node health
{"status":"The Seq node is in service."}
```
With the flag (similar output to today):
```
> seqcli node health --verbose
HTTP 1.1 200 OK
Date: Mon, 08 Jul 2024 04:16:13 GMT
Transfer-Encoding: chunked
Connection: keep-alive
Vary: Accept-Encoding
...
{"status":"The Seq node is in service."}
```
No `--json` flag is currently required - the output is always the literal response from the server, for easy diagnostics (e.g. when the actual response is some random HTML page from a proxy/gateway). Could reevaluate this down the track.
> Only include detailed HTTP diagnostics in `node health` output when `--verbose` is set

- src/SeqCli/Cli/Commands/ApiKey/CreateCommand.cs
An oversight when this was added in 2022 (or thereabouts).
> Add Organization to the list of permissions documented for the `apikey create` command

- src/SeqCli/Cli/Commands/ConfigCommand.cs
- src/SeqCli/Cli/Commands/Profile/CreateCommand.cs
- src/SeqCli/Cli/Commands/Profile/ListCommand.cs
- src/SeqCli/Cli/Commands/Profile/RemoveCommand.cs
- src/SeqCli/Cli/Options.cs
- src/SeqCli/Config/EnvironmentOverrides.cs
- src/SeqCli/Config/KeyValueSettings.cs
- src/SeqCli/Config/RuntimeConfigurationLoader.cs
- src/SeqCli/Config/SeqCliConfig.cs
- src/SeqCli/SeqCliModule.cs
- src/SeqCli/Syntax/QueryBuilder.cs
- test/SeqCli.Tests/Config/EnvironmentOverridesTests.cs
- test/SeqCli.Tests/PlainText/NameValueExtractorTests.cs
Fixes #365 
The README shows how environment variable setting overrides _should_ work, but this was committed in error, the README updates should have gone to Seq Forwarder, which was the project that gained environment override support at that time.
Instead of fixing the README, I've lined up `seqcli`'s configuration handling with Seq's - this should help us along towards a fully-consistent experience across client and server in the future.
`SEQCLI_CONNECTION_SERVERURL` now works:
```
seqcli> SEQCLI_CONNECTION_SERVERURL=https://test.example.com seqcli log -m test 
The command failed: nodename nor servname provided, or not known (test.example.com:443) nodename nor servname provided, or not known
seqcli> seqcli log -m test
The command failed: Connection refused (localhost:5341) Connection …
```
> Align `seqcli`'s environment override handling with Seq's

- src/SeqCli/Config/EnvironmentOverrides.cs
- src/SeqCli/Config/KeyValueSettings.cs
- src/SeqCli/Config/RuntimeConfigurationLoader.cs
- src/SeqCli/Config/SeqCliConfig.cs
- src/SeqCli/Properties/launchSettings.json
This restores behavior broken in #366 - the `connection.apiKey` value relies on user writes to the property with `seqcli config` going through the `ApiKey` property rather than the user-visible `EncodedApiKey` property.
The behavior change led to an exception rather than exposure of any sensitive info, but this whole mechanism could do with some further hardening and test coverage.
> Fix exception when writing `connection.apiKey` values

- README.md
- src/SeqCli/Cli/Commands/Dashboard/ListCommand.cs
- src/SeqCli/Cli/Commands/Dashboard/RemoveCommand.cs
- src/SeqCli/Cli/Commands/Signal/ImportCommand.cs
- src/SeqCli/Cli/Commands/Signal/ListCommand.cs
- src/SeqCli/Cli/Commands/Signal/RemoveCommand.cs
- src/SeqCli/Cli/Commands/Workspace/ListCommand.cs
- src/SeqCli/Cli/Commands/Workspace/RemoveCommand.cs
- src/SeqCli/Cli/Features/EntityOwnerFeature.cs
Fixes API documentation misspellings. 
https://github.com/datalust/seq-tickets/issues/2384
> Fix past participles of command verbs. e.g. removd => removed

- src/SeqCli/Cli/Commands/Bench/BenchCases.json
Aggregate query caching breaks the statistics generated from bench results, hence it is better to opt out of aggregate query caching for query benchmarking.
> Add `no_cache` directive to bench queries.

- src/SeqCli/Cli/Commands/Cluster/HealthCommand.cs
- src/SeqCli/Cli/Commands/Node/HealthCommand.cs
- src/SeqCli/Cli/Features/WaitUntilHealthyFeature.cs
- test/SeqCli.EndToEnd/Node/NodeHealthTestCase.cs
Makes output consistent with the command's help text, showing status code unless `--json` is specified, in which case we use regular JSON output.
Adds `--wait-until-healthy` and `--timeout` to assist with deployment automation scenarios.
There are some subtle differences between the semantics of `/health` and `/health/cluster` that make further convergence tricky, but there's still room to revisit and improve this command in the future.
> Update the `node health` command to be roughly comparable with `cluster health`

- src/SeqCli/Cli/Commands/Sample/IngestCommand.cs
- src/SeqCli/Cli/Commands/Sample/SetupCommand.cs
- test/SeqCli.EndToEnd/Sample/SampleIngestTestCase.cs
- test/SeqCli.EndToEnd/Support/CliCommandRunner.cs
This PR introduces a `--setup` flag to `seqcli sample ingest` that lets you import the setup templates and run sample ingestion in a single command:
```
seqcli sample ingest --setup -y
```
> Add a --setup flag to sample ingest

- src/SeqCli/Cli/Commands/License/ShowCommand.cs
- test/SeqCli.EndToEnd/License/LicenceShowTestCase.cs
Relevant issue here #373 
There are some open points for discussion:
I use the `OutputFormatFeature` like other commands do. This enables `--json` output, which looks great. But without `--json` it just prints `license-server`, which is not very informative.
I currently find no way to behave the `OutputFormatter.WriteEntity` in a different way, because it has like a constant format string `$"{entity.Id} {dyn.Title ?? dyn.Name ?? dyn.Username ?? dyn.Expression}"`.
I could:
* Check if `!_output.Json` and create a DTO object for output like `new {Id=license.SubscriptionId}` so this get printed instead.
* Don't use `_output` but write directly to the console / Serilog
* Document the behaviour and instruct the user to use `--json`
EDIT: I've implemented a OutputWrapperLicenseEntity for better …
> `license show` command 

- src/SeqCli/Cli/CommandAttribute.cs
- src/SeqCli/Cli/CommandLineHost.cs
- src/SeqCli/Cli/CommandMetadata.cs
- src/SeqCli/Cli/Commands/Config/ClearCommand.cs
- src/SeqCli/Cli/Commands/Config/GetCommand.cs
- src/SeqCli/Cli/Commands/Config/LegacyCommand.cs
- src/SeqCli/Cli/Commands/Config/ListCommand.cs
- src/SeqCli/Cli/Commands/Config/SetCommand.cs
- src/SeqCli/Cli/Commands/Forwarder/InstallCommand.cs
- src/SeqCli/Cli/Commands/Forwarder/RestartCommand.cs
- src/SeqCli/Cli/Commands/Forwarder/RunCommand.cs
- src/SeqCli/Cli/Commands/Forwarder/StartCommand.cs
- src/SeqCli/Cli/Commands/Forwarder/StatusCommand.cs
- src/SeqCli/Cli/Commands/Forwarder/StopCommand.cs
- src/SeqCli/Cli/Commands/Forwarder/TruncateCommand.cs
- src/SeqCli/Cli/Commands/Forwarder/UninstallCommand.cs
- src/SeqCli/Cli/Commands/HelpCommand.cs
- src/SeqCli/Cli/FeatureVisibility.cs
- src/SeqCli/Cli/Features/ConfigKeyFeature.cs
- src/SeqCli/Cli/Features/ConfigValueFeature.cs
- test/SeqCli.Tests/Cli/CommandLineHostTests.cs
Could definitely be a bit more elegant 😅 but this does at least remove the endlessly-annoying papercut typing `seqcli config <something>` expecting Seq's `config` subcommands to be available.
> Switch `config` command to a command group, including `clear`, `get`, `set`, and `list` to match Seq's CLI

- build/Build.Windows.ps1
- src/SeqCli/Forwarder/Util/CaptiveProcess.cs
- test/SeqCli.EndToEnd/Support/TestConfiguration.cs
This PR ensures we also run seqcli's end-to-end test suite on Windows hosts, since there is some small amount of platform-specific code involved.
> Run end-to-end tests on Windows

- src/SeqCli/SeqCli.csproj
Adds support for anti-CSRF tokens, which will become mandatory from Seq 2026.1.
> Update to Seq.Api 2025.2.2
