datalust/seqcli

- Build.ps1
- setup/SeqCli.Setup/Product.wxs
- setup/SeqCli.Setup/SeqCli.Setup.wixproj
> Fix installer versioning

- README.md
* #51 - correct handling of invalid JSON with `ingest --json`
> New Preview

- README.md
- src/SeqCli/Cli/Commands/HelpCommand.cs
Rendered: https://github.com/datalust/seqcli/blob/65d1fef60c23fe53cd823962fd4d1a4682122341/README.md#commands
> Include command ToC in generated help

- README.md
- src/SeqCli/Cli/Features/SendFailureHandlingFeature.cs
- src/SeqCli/Ingestion/LogShipper.cs
- src/SeqCli/Ingestion/SendFailureHandling.cs
> Add a simple exponential-backoff retry strategy for ingestion

- README.md
- appveyor.yml
- src/SeqCli/Api/ApiConstants.cs
- src/SeqCli/Cli/Commands/IngestCommand.cs
- src/SeqCli/Cli/Commands/LogCommand.cs
- src/SeqCli/Connection/SeqConnectionFactory.cs
- src/SeqCli/Ingestion/LogShipper.cs
* #81 - fixes a bug whereby API keys are not sent correctly when logging/ingesting events
> 5.0 Maintenance Release

- README.md
Just adds a note pointing to Docker support in the readme.
> Add note about the docker container

- Build.ps1
- SeqCli.Runtime.targets
- seqcli.sln
- src/SeqCli/Program.cs
- src/SeqCli/SeqCli.csproj
Ensures Windows proxy settings etc. are respected. From #86.
> Opt out of managed sockets on Windows

- src/SeqCli/SeqCli.csproj
> Update to a version of Serilog.Filters.Expressions compatible with Superpower 2.0

- src/SeqCli/Cli/Features/OutputFormatFeature.cs
- test/SeqCli.EndToEnd/ApiKey/ApiKeyCreateTestCase.cs
- test/SeqCli.EndToEnd/Dashboard/RenderTestCase.cs
- test/SeqCli.EndToEnd/Signal/SignalBasicsTestCase.cs
> Convert enums to strings in JSON output representing entities

- src/SeqCli/SeqCli.csproj
- test/SeqCli.EndToEnd/SeqCli.EndToEnd.csproj
- test/SeqCli.EndToEnd/Support/TestDriver.cs
> Final 5.1.0 API client

- src/SeqCli/Cli/Commands/IngestCommand.cs
- src/SeqCli/Ingestion/EnrichingReader.cs
- src/SeqCli/Ingestion/ILogEventReader.cs
- src/SeqCli/Ingestion/LogShipper.cs
- src/SeqCli/Ingestion/StaticMessageTemplateReader.cs
- src/SeqCli/PlainText/PlainTextLogEventReader.cs
- test/SeqCli.Tests/PlainText/StaticMessageTemplateReaderTests.cs
- test/SeqCli.Tests/Support/FixedLogEventReader.cs
- test/SeqCli.Tests/Support/Some.cs
> -m and -l syntax for overriding message and level on ingestion

- dockerfiles/seqcli/run.sh
> Double-quote forwarded arguments in run.sh

- docker-publish.ps1
To keep the manual part of our Docker publish process consistent with other projects.
> Add a docker publish script

- seqcli.sln.DotSettings
- src/SeqCli/Cli/Commands/QueryCommand.cs
> Apply `query --timeout` to HttpClient

- src/SeqCli/Cli/Commands/Dashboard/RenderCommand.cs
- src/SeqCli/Cli/Commands/QueryCommand.cs
- src/SeqCli/Cli/Features/TimeoutFeature.cs
- test/SeqCli.Tests/Cli/NoDuplicateCommands.cs
- test/SeqCli.Tests/PlainText/FrameReaderTests.cs
> Apply timeout to HttpClient in the dashboard render command

- src/SeqCli/Cli/Commands/ApiKey/CreateCommand.cs
- src/SeqCli/Cli/Commands/Signal/CreateCommand.cs
- src/SeqCli/Cli/Commands/User/CreateCommand.cs
- src/SeqCli/SeqCli.csproj
Just mechanical changes, here.
> Update to the latest 2020.1 API version

- Build.ps1
Hi,
I ran into an issue trying to use this with alpine. My understanding is we need a musl build to support alpine.
Cheers,
Andrew
> Add support for Alpine linux containers

- SeqCli.Runtime.targets
- src/SeqCli/SeqCli.csproj
Sorry @nblumhardt I missed 2 files in #149
> Fix missing locations for new RID

- Build.Docker.ps1
- test/SeqCli.EndToEnd/SeqCli.EndToEnd.csproj
- test/SeqCli.EndToEnd/Support/CaptiveProcess.cs
- test/SeqCli.EndToEnd/Support/TestConfiguration.cs
Enable End to End tests for each commit against latest docker image
> Run EndToEnd tests on every commit

- src/SeqCli/Cli/Commands/Sample/IngestCommand.cs
- src/SeqCli/Sample/Loader/Simulation.cs
A very simple quality-of-life improvement when using `seqcli sample ingest` for load testing :-)
> Quiet flag for seqcli sample ingest

- Build.ps1
Let's see if this is all we need to do to get arm builds for `seqcli` 🤞
> Publish arm builds of seqcli

- appveyor.yml
- dockerfiles/seqcli/Dockerfile
- dockerfiles/seqcli/run.sh
Some overdue housekeeping and clean-up.
> Remove run.sh, update to Ubuntu 20.04 base image, switch builds to use pwsh

- src/SeqCli/Cli/Commands/ApiKey/CreateCommand.cs
- src/SeqCli/SeqCli.csproj
> Fix documentation of permissions in apikey create. Fix bug parsing permissions. Platform additions from seq.

- docker-publish.ps1
Just fixes up some issues in the Docker publish script
> Escape variables in strings

- Build.Docker.ps1
- README.md
- appveyor.yml
- setup.sh
> 2022.1.579 Release

- Build.Docker.ps1
- dockerfiles/seqcli/linux-arm64.Dockerfile
- dockerfiles/seqcli/linux-x64.Dockerfile
- setup.sh
- src/SeqCli/SeqCli.csproj
- src/SeqCli/Util/Content.cs
It looks like publishing on ARM is still not quite working, so this PR makes a few trivial adjustments to reduce the number of moving parts.
> More docker publishing tweaks

- appveyor.yml
The version number was not updated in the previous release PR.
> 2023.3 Release (attempt 2)

- test/SeqCli.EndToEnd/SeqCli.EndToEnd.csproj
Should fix up the build failure in #312
> Fix up end to end project

- appveyor.yml
> 2024.2 versioning update

- src/SeqCli/Cli/Commands/AppInstance/CreateCommand.cs
Same example as the other commands that accept signal expressions
> Add example signal expression

- src/Roastery/Roastery.csproj
- src/SeqCli/SeqCli.csproj
- test/SeqCli.EndToEnd/SeqCli.EndToEnd.csproj
- test/SeqCli.Tests/SeqCli.Tests.csproj
> Update all NuGet dependencies

- src/SeqCli/Levels/LevelMapping.cs
> Map syslog alert level to fatal

- src/SeqCli/Cli/Commands/Bench/BenchCases.json
- src/SeqCli/Cli/Commands/Bench/BenchCommand.cs
This test is very slow on moderate size logs.
> Order by message bench case range and case sensitivity

- src/SeqCli/SeqCli.csproj
https://github.com/datalust/seq-app-mail/pull/30
> Update `Seq.Syntax` to pull in better tracing support for templated apps
